# logic_ai_provider.py

from typing import Dict, Optional
from vertexai.preview.generative_models import GenerativeModel


# ==============================
# Base Interface
# ==============================

class AIProvider:
    def explain_recommendation(self, *, question: str, context: Dict) -> str:
        raise NotImplementedError


# ==============================
# Fallback Provider
# ==============================

class MockAIProvider(AIProvider):
    def explain_recommendation(self, *, question: str, context: Dict) -> str:
        rb = context.get("rule_based_summary", {})

        return (
            "🧠 AI Advisor (Rule-Based Fallback)\n\n"
            "⚠️ External AI unavailable.\n\n"
            f"Question: {question}\n\n"
            f"Recommendation: {rb.get('recommendation', 'N/A')} "
            f"Score: {rb.get('score', 'N/A')} "
            f"Confidence: {rb.get('confidence', 'N/A')}\n\n"
            "This response is generated from internal logic only."
        )


# ==============================
# Vertex Gemini Provider
# ==============================

class GeminiVertexProvider(AIProvider):
    def __init__(self):
        self.model = GenerativeModel("gemini-2.5-flash")

    def explain_recommendation(self, *, question: str, context: Dict) -> str:
        rb = context.get("rule_based_summary", {})
        system_rules = context.get("system_rules", "")

        prompt = f"""
{system_rules}

Investor Question:
{question}

Rule-Based Summary:
Recommendation: {rb.get('recommendation')}
Score: {rb.get('score')}
Confidence: {rb.get('confidence')}
Risk Profile: {rb.get('risk_profile')}
Reasons: {rb.get('reasons')}
Market: {rb.get('market')}
"""

        response = self.model.generate_content(
            prompt,
            generation_config={
                "temperature": 0.3,
                "max_output_tokens": 1024,
            },
        )

        if response.candidates and response.candidates[0].content.parts:
            return response.candidates[0].content.parts[0].text
        else:
            return "⚠️ No response generated by Gemini."


# ==============================
# Provider Selector
# ==============================

def get_ai_provider(provider_name: Optional[str] = None) -> AIProvider:
    try:
        return GeminiVertexProvider()
    except Exception:
        return MockAIProvider()
