# logic_ai_provider.py

from typing import Dict, Optional
from vertexai.preview.generative_models import GenerativeModel


# ==============================
# Base Interface
# ==============================

class AIProvider:
    def explain_recommendation(self, *, question: str, context: Dict) -> str:
        raise NotImplementedError


# ==============================
# Fallback Provider
# ==============================

class MockAIProvider(AIProvider):
    def explain_recommendation(self, *, question: str, context: Dict) -> str:
        rb = context.get("rule_based_summary", {})

        return (
            "🧠 AI Advisor (Rule-Based Fallback)\n\n"
            "⚠️ External AI unavailable.\n\n"
            f"Question: {question}\n\n"
            f"Recommendation: {rb.get('recommendation', 'N/A')} "
            f"Score: {rb.get('score', 'N/A')} "
            f"Confidence: {rb.get('confidence', 'N/A')}\n\n"
            "This response is generated from internal logic only."
        )


# ==============================
# Vertex Gemini Provider
# ==============================

class GeminiVertexProvider(AIProvider):
    def __init__(self):
        self.model = GenerativeModel("gemini-2.5-flash")

    def explain_recommendation(self, *, question: str, context: Dict) -> str:
        rb = context.get("rule_based_summary", {})
        system_rules = context.get("system_rules", "")

        prompt = f"""
{system_rules}

You are an experienced investment advisor helping a disciplined investor.

Investor Question:
{question}

===== INVESTMENT CONTEXT =====

Recommendation: {rb.get('recommendation')}
Score: {rb.get('score')}
Confidence: {rb.get('confidence')}
Risk Profile: {rb.get('risk_profile')}

Key Signals:
{rb.get('reasons')}

Market Regime:
{rb.get('market')}

Investor Profile:
Conservative investor focused on risk control and disciplined exits.

Investment Philosophy:
• Avoid excessive leverage
• Prefer strong cash flow
• Protect capital first
• Seek sustainable growth

===== TASK =====

Provide a structured investment analysis using the sections below.

1. Independent AI Assessment
Provide your own unbiased view on the stock.

2. Latest News & Macro Environment
Analyze recent news, sector developments, and global macro factors.

3. Risks Possibly Underestimated
Highlight risks the rule engine may miss.

4. Signals Possibly Overlooked
Mention additional factors worth monitoring.

5. What I Would Watch Going Forward
Provide practical investor guidance.

Be independent. Do not rely only on rule-based output.
"""

        response = self.model.generate_content(
            prompt,
            generation_config={
                "temperature": 0.2,
                "max_output_tokens": 4500,
            },
        )

        if response.candidates:
            text_output = ""

            for part in response.candidates[0].content.parts:
                if hasattr(part, "text") and part.text:
                    text_output += part.text

            return text_output.strip()

        else:
            return "⚠️ No response generated by Gemini."

# ==============================
# Provider Selector
# ==============================

def get_ai_provider(provider_name: Optional[str] = None) -> AIProvider:
    try:
        return GeminiVertexProvider()
    except Exception:
        return MockAIProvider()
